### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by devin5411** [ThePocketKings/TrollPlayer#1]
How do I install this to my server or can you make it a .phar?

**Comment by Ivanzar** [comment]
@devin5411 You must to download from the official site DevTools

**Comment by devin5411** [comment]
Can I have the link?

On Saturday, May 23, 2015, Ivan Zarubin <notifications@github.com> wrote:

> @devin5411 <https://github.com/devin5411> You must to download from the
> official site DevTools
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThePocketKings/TrollPlayer/issues/1#issuecomment-104877216>
> .
>


-- 
*Devin*

**Comment by Ivanzar** [comment]
https://forums.pocketmine.net/plugins/devtools.515/

**Comment by devin5411** [comment]
Oh I thought u meant the site of devtools thanks though so I just make it a
.phar?

On Sunday, May 24, 2015, Ivan Zarubin <notifications@github.com> wrote:

> https://forums.pocketmine.net/plugins/devtools.515/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThePocketKings/TrollPlayer/issues/1#issuecomment-104993187>
> .
>


-- 
*Devin*
